//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundamentals.Resources.Math {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fibonacci {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fibonacci() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fundamentals.Resources.Math.Fibonacci", typeof(Fibonacci).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19837779011484912110559461611897879824756662368828587378125731561244809005006588121371157164936707185586771181243260782820753286323520090182436562876438635116476960211306972832533222236863626016800172539014814722044065130102307440630952925074514503935605189532219940195992194790816269264251180087247848390441574201688900421547904076394811580169955215549714375849278874613124202394423267087287281742933642142183231631120006129957572708387453830319393805616697066233355102111922953112963415574208931037616950346995 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IntMax8192 {
            get {
                return ResourceManager.GetString("IntMax8192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35360880361910251126452669455620308660387507262425657057941083714154016794650589093384647824004993283027919607313323939587481595067472222147134949170928115661357214587989286173693816255284833068378030216363059713367182324054573396403520361220032505500441451957563674720887468066323851738392466777300957187437418311062000915453475751361169324293137342122365125588462334147487218603694369156524550864145525735730636023463266706293695003418558236279483304782942750830399629534398043401675124704063553894843835089507 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShortMax {
            get {
                return ResourceManager.GetString("ShortMax", resourceCulture);
            }
        }
    }
}
